# davetcoleman/moveit_docker:jade-base
# Somewhat mimmics ros-jade-desktop

FROM ros:jade-ros-base
MAINTAINER Dave Coleman dave@dav.ee

RUN apt-get update && \
    apt-get upgrade -y

RUN apt-get install -y ros-jade-rviz